# Site Settings
title: Cursuri sus»õinute de TSS-Yonder
url: "https://courses.tss-yonder.com"
baseurl: null
paginate_path: resurse/pagina-:num/
permalink: resurse/:categories/:title/
force-https: True
lang: "ro"
paginate: 5
google-tracking-id: "UA-99139394-1"

# Build Settings
markdown:           kramdown
kramdown:
  input:            GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false

# Enable minification SASS
sass:
  sass_dir:         assets/css
  style:            compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

exclude:
  - CONTRIBUTING
  - CONTRIBUTORS
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore
  - .travis.yml
  - .build

# Settings for build
relative_source: "../courses.tss-yonder.com/"
destination:     "../courses.tss-yonder.com-pages/"
